add_newline = true

[character]
success_symbol = "[>](bold green)"
error_symbol = "[✗](bold red)"

[username]
style_user = "white bold"
style_root = "black bold"
format = "user: [$user]($style) "
disabled = false
show_always = true

[directory]
truncation_length = 100
truncate_to_repo = false

[memory_usage]
disabled = false
threshold = -1
style = "bold dimmed green"
format = "via [${ram_pct} / ${swap_pct}]($style) "

[package]
disabled = true

[time]
disabled = false
format = '[\[ $time \]]($style) '